### PR TITLE
Fix Dict warning

### PR DESCRIPTION
**Pull request by yuyichao**

### CODE REVIEW

**Comment by yuyichao** [comment]
Error from CI seems to come from `WinRPM`?

**Comment by tkelman** [comment]
@amitmurthy needs to tag LibExpat.jl

**Comment by amitmurthy** [comment]
Done.

**Comment by tkelman** [comment]
Thanks! (also for adding me as collab, good to have backup options for anything urgent if you go on vacation or otherwise offline)

**Comment by tkelman** [comment]
oh, did I manage to break things? `type: xpath_expr: in typeassert, expected Array{(Symbol,Any),1}, got Array{(Any...,),1}` whoops

**Comment by amitmurthy** [comment]
LibExpat tests pass fine on 0.4. Issue with `@compat`?

**Comment by tkelman** [comment]
It also passes on 0.3.7 on Ubuntu 14.04, so hopefully not. It might actually be an upstream opensuse build service thing, the xml might actually be bad.

**Comment by yuyichao** [comment]
Ping. I've rebased this to the latest master and it seems that the CI tests pass as well after the issues in the dependencies have been fixed. Is there any other issues that prevent this to be merged?

**Pull request merged**
