### PR TITLE
Use Julia 0.5 on Travis

### PR DESCRIPTION
**Pull request by simonbyrne**

### CODE REVIEW

**Comment by tkelman** [comment]
if you want to tag this soon it should drop 0.3 support and bump minor at the next package tag too

**Comment by simonbyrne** [comment]
So don't tag a release with 0.3 support?

**Comment by tkelman** [comment]
yeah, metadata is frozen for 0.3-supporting packages, no new tags unless there's a critical need to fix something that was previously working on 0.3

**Comment by simonbyrne** [comment]
ok, will do.

**Pull request merged**
