### PR TITLE
Enable appveyor

### PR DESCRIPTION
**Pull request by tkelman**
I have this on my account for now, we could move it to someone else's if needed.

### CODE REVIEW

**Comment by stevengj** [comment]
Looks like the appveyor build is failing on windows...
```
Provider PackageManager failed to satisfy dependency zmq
while loading C:\Users\appveyor\.julia\v0.3\ZMQ\deps\build.jl, in expression starting on line 22
```

**Comment by tkelman** [comment]
on stable. if the queue weren't so interminably long this would be able to verify whether it's working on nightly now that my fix was merged on Julia master

**Comment by tkelman** [comment]
I got impatient and cancelled the original build, after 3 hours it was probably stuck.

Restarting as shown in this second build should, I believe, make things work on stable as well. I'll try to remember to check just nightlies at some future point (or if your account's appveyor queue is idle you can fork this branch and test)

**Comment by jakebolewski** [comment]
Gaa, I pressed the button by mistake.  Hopefully it is ok.

**Comment by tkelman** [comment]
doesn't really hurt anything

**Pull request merged**
