### PR TITLE
Add AptGet provider

### PR DESCRIPTION
**Pull request by simonbyrne**
Partially addresses #45

### CODE REVIEW

**Comment by alexmorley** [comment]
I had to change this to Yum on my machine (Fedora 25) to avoid build errors.

**Comment by nalimilan** [comment]
@alexmorley Though if you remove that line it should fail too, right? That just means we should add a line for Yum too. Could you make a PR for that?

**Comment by alexmorley** [comment]
I think there might be an issue with the BinDeps as if I put the Yum provides after then it still tries to apt-get and then errors... See https://github.com/JuliaLang/BinDeps.jl/issues/250

**Comment by alexmorley** [comment]
Also it actually builds fine if I just remove the Apt-Get line without adding yum

**Comment by nalimilan** [comment]
OK. Adding a yum line wouldn't hurt though.

**Pull request merged**
