### PR TITLE
Union() -> Union{}

### PR DESCRIPTION
**Pull request by yuyichao**
And enable 0.3 and 0.4 on travis.

### CODE REVIEW

**Comment by stevengj** [comment]
We desperately need a new version of LibExpat to be tagged... I'm not having difficulty scrolling through the thousands of lines of warning messages to discover the actual AppVeyor error.  I'm at over 15,000 lines of warnings and it is still loading more.

**Comment by yuyichao** [comment]
I think @tkelman [is at it](https://github.com/JuliaLang/METADATA.jl/pull/3474)

**Comment by yuyichao** [comment]
And I think the actual AppVeyor error is timeout, due to the slowness of deprecated functions....

**Comment by stevengj** [comment]
Restart AppVeyor or do forced push?

**Comment by yuyichao** [comment]
force pushed

**Pull request merged**
